"""add vendor address for manifest destination

Revision ID: c1f583dd0272
Revises: f60b94996c9b
Create Date: 2026-08-02 08:35:35.833009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1f583dd0272'
down_revision = 'f60b94996c9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate wanted to drop the idx_* performance indexes from revision
    # a1b2c3d4e5f6 because they are not declared on the models. They are intentional -
    # those drops have been removed here.

    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address1', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('address2', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('zip', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.drop_column('zip')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('address2')
        batch_op.drop_column('address1')

    # ### end Alembic commands ###
