"""add trip order items, email contacts, driver dob, vehicle details

Revision ID: f60b94996c9b
Revises: drop_customer_contact
Create Date: 2026-08-02 08:32:53.714286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f60b94996c9b'
down_revision = 'drop_customer_contact'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_mapping_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_mapping_id'], ['location_mapping.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trip_order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_order_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=300), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('parent_barcode_id', sa.String(length=50), nullable=True),
    sa.Column('sublot_barcode_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trip_order_id'], ['trip_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dob', sa.String(length=10), nullable=True))

    # NOTE: autogenerate wanted to drop the idx_* performance indexes from revision
    # a1b2c3d4e5f6 because they are not declared on the models. They are intentional -
    # those drops have been removed here.

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vin', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('make', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('model', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('plate', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('year', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_column('year')
        batch_op.drop_column('plate')
        batch_op.drop_column('model')
        batch_op.drop_column('make')
        batch_op.drop_column('color')
        batch_op.drop_column('vin')

    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.drop_column('dob')

    op.drop_table('trip_order_item')
    op.drop_table('email_contact')
    # ### end Alembic commands ###
